abonos:
    path:  /
    defaults: { _controller: "lOroTransferenciasBundle:Abonos:index" }
    
    
abono_new:
    path:  /new
    defaults: { _controller: "lOroTransferenciasBundle:Abonos:new" }
    
abono_show:
    path:  /show/{id}
    defaults: { _controller: "lOroTransferenciasBundle:Abonos:show" }  
    
abono_delete:
    path:  /delete/{id}
    defaults: { _controller: "lOroTransferenciasBundle:Abonos:delete" } 
    
abono_edit:
    path:  /edit/{id}
    defaults: { _controller: "lOroTransferenciasBundle:Abonos:edit" }     