debitos:
    path:  /
    defaults: { _controller: "lOroTransferenciasBundle:Debitos:index" }
    
    
debitos_new:
    path:  /new
    defaults: { _controller: "lOroTransferenciasBundle:Debitos:new" }
    
debitos_show:
    path:  /show/{id}
    defaults: { _controller: "lOroTransferenciasBundle:Debitos:show" }  
    
debitos_delete:
    path:  /delete/{id}
    defaults: { _controller: "lOroTransferenciasBundle:Debitos:delete" } 
    
debitos_edit:
    path:  /edit/{id}
    defaults: { _controller: "lOroTransferenciasBundle:Debitos:edit" }    
