pagos-varios:
    path:  /
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:index" }

pagos-varios_show:
    path:  /{id}/show
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:show" }

pagos-varios_new:
    path:  /new
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:new" }

pagos-varios_create:
    path:  /create
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:create" }
    requirements: { methods: post }

pagos-varios_edit:
    path:  /{id}/edit
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:edit" }

pagos-varios_update:
    path:  /{id}/update
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:update" }
    requirements: { methods: post|put }

pagos-varios_delete:
    path:  /{id}/delete
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:delete" }
#    requirements: { _method: post|delete }

_buscador_pagos_varios:
    path:  /buscador-pagos-varios
    defaults: { _controller: "lOroTransferenciasBundle:PagosVarios:buscarPagosVarios" }  