services:
  loro.listener.maintenance:
    class: lOro\AppBundle\Listener\MaintenanceListener
    arguments:
      container: "@service_container"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
