inicio:
    path: l_oro/index
    defaults: { _controller: lOroinicioBundle:Default:index }

_buscar_info_proveedor:
    path: inicio/buscar-info-proveedor
    defaults: { _controller: lOroinicioBundle:Default:buscarInfoProveedor}
    
_cierres_del_dia:
    path: /cierres-del-dia
    defaults: { _controller: lOroinicioBundle:Default:cierresDelDia }    


_homepage_balance_bs:
    path: inicio/homepage-balance-bs
    defaults: { _controller: lOroinicioBundle:Default:balanceBolivares }

_homepage_balance_grams:
    path: inicio/homepage-balance-grams
    defaults: { _controller: lOroinicioBundle:Default:balanceMaterial }

_homepage_balance_by_suppliers:
    path: inicio/homepage-balance-by-suppliers
    defaults: { _controller: lOroinicioBundle:Default:balanceBySuppliers }

_homepago_balance_by_retail_suppliers:
    path: inicio/homepage-balance-by-retail-suppliers
    defaults: { _controller: lOroinicioBundle:Default:balanceByRetailSuppliers }    