parameters:
#    l_oro_balance.example.class: lOro\BalanceBundle\Example

services:
#    l_oro_balance.example:
#        class: %l_oro_balance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
