login:
    path:  /login
    defaults: { _controller: lOroLoginBundle:Security:login }
    
logout:
    path:  /logout
    defaults: { _controller: lOroLoginBundle:Security:logout } 
    
login_check:
    path: /login_check    

cambiar_contrasena:
    path: /cambio-contrasena
    defaults: { _controller: lOroLoginBundle:Security:cambiarContrasena }
    
    
cargar:
    path: /cargar
    defaults: { _controller: lOroLoginBundle:Security:cargarUser }