login:
    pattern:  /login
    defaults: { _controller: lOroLoginBundle:Security:login }
    
logout:
    pattern:  /logout
    defaults: { _controller: lOroLoginBundle:Security:logout } 
    
login_check:
    pattern: /login_check    

cambiar_contrasena:
    pattern: /cambio-contrasena
    defaults: { _controller: lOroLoginBundle:Security:cambiarContrasena }
    
    
cargar:
    pattern: /cargar
    defaults: { _controller: lOroLoginBundle:Security:cargarUser }