security:
    encoders:
        lOro\EntityBundle\Entity\Users:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
    providers:
        main:
            entity:
                class: lOro\EntityBundle\Entity\Users
                property: username



    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPERUSER, ROLE_USER, ROLE_PROVEEDOR, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/
            form_login:
                login_path: /login
                check_path: /login_check
                success_handler: redirect.after.login
                csrf_token_generator: security.csrf.token_manager
            anonymous: ~
        relacion_entregas_firewall:
            pattern:   ^/admin/relacionar-entregas-cierres-aupanas-hc$
            anonymous: ~            
        secured_area:
            pattern:    ^/
            form_login: ~
            logout:
                path: /logout
                target: /

    access_control:
         - { path: ^/admin/relacionar-entregas-cierres-aupanas-hc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/servicios, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/cargar, roles: IS_AUTHENTICATED_ANONYMOUSLY }    
         - { path: ^/app-proveedores/*, roles: ROLE_PROVEEDOR } 
         - { path: ^/cambio-contrasena, roles: [ROLE_PROVEEDOR, ROLE_USER, ROLE_SUPERUSER] }
         - { path: ^/entregas/[0-9]+/show$, roles: [ROLE_PROVEEDOR, ROLE_USER, ROLE_SUPERUSER,ROLE_REGISTRADOR_CIERRES] }
         - { path: ^/, roles: [ROLE_USER, ROLE_SUPERUSER,ROLE_REGISTRADOR_CIERRES] }
