parameters:
#    l_oro_entregas.example.class: lOro\EntregasBundle\Example

services:
#    l_oro_entregas.example:
#        class: %l_oro_entregas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
