pagos_minoristas:
    path:  /
    defaults: { _controller: "lOroPagosBundle:PagosMinoristas:index" }
    
pagos_minoristas_new:
    path:  /new
    defaults: { _controller: "lOroPagosBundle:PagosMinoristas:new" }    
    
pagos_minoristas_create:
    path:  /create
    defaults: { _controller: "lOroPagosBundle:PagosMinoristas:create" }      
