ventas_cierres_proveedores:
    path:  /cierres-proveedores
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:index" ,lugar: proveedores }
    
ventas_cierres_proveedores_new:
    path:  /new-proveedores
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:new",lugar: proveedores }
    
ventas_cierres_proveedores_create:
    path:  /create-proveedores
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:create",lugar: proveedores }
    requirements: { methods: post }

ventas_cierres_proveedores_edit:
    path:  /{id}/edit
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:edit" ,lugar: proveedores }
    
ventas_cierres_proveedores_update:
    path:  /{id}/update
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:update",lugar: proveedores }
    requirements: { methods: post|put }    
    
ventas_cierres_proveedores_show:
    path:  /{id}/show-proveedores
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:show",lugar: proveedores }
    
ventas_cierres_proveedores_delete:
    path:  /{id}/delete-proveedores
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:delete",lugar: proveedores }
  
    
# Rutas de los Cierres con HC 
ventas_cierres_hc:
    path:  /cierres-hc
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:index", lugar: hc }    
    
ventas_cierres_hc_new:
    path:  /new-hc
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:new",lugar: hc }
    
ventas_cierres_hc_create:
    path:  /create-hc
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:create",lugar: hc }
    requirements: { methods: post }    
    
ventas_cierres_hc_edit:
    path:  /{id}/edit-hc
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:edit",lugar: hc }
    
ventas_cierres_hc_update:
    path:  /{id}/update-hc
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:update",lugar: hc }
    requirements: { methods: post|put }
    
ventas_cierres_hc_show:
    path:  /{id}/show-hc
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:show",lugar: hc }
    
ventas_cierres_hc_delete:
    path:  /{id}/delete-hc
    defaults: { _controller: "lOroVentasCierreBundle:VentasCierres:delete",lugar: hc } 